

// CUSTOMER_IDE, NAME, CITY, STATE, PRICE, TAX_PRICE

// PEGAR TODOS OS ÍTENS
// SELECIONAR ID E NOME
SELECT * FROM CUSTOMER;
SELECT CUSTOMER_ID, NAME FROM CUSTOMER;
SELECT CITY FROM CUSTOMER;
SELECT STATE FROM CUSTOMER;
SELECT NAME, CITY FROM CUSTOMER;

// ADICIONAR COLUNA EM TABELA JÁ EXISTENTE 
ALTER TABLE CUSTOMER ADD COLUMN PRICE REAL;
ALTER TABLE CUSTOMER ADD COLUMN TAX_PRICE REAL;

// DELETER COLUNA 
ALTER TABLE CUSTOMER DROP COLUMN PRICE;
ALTER TABLE CUSTOMER DROP COLUMN TAX_PRICE;

// ADICIONAR VALORES IGUAIS PARA TODOS AS PROPRIEDADES DE VALORES
UPDATE CUSTOMER 
SET PRICE = 100;

// CALCULAR UM VALOR 
SELECT CUSTOMER_ID, PRICE, PRICE * 1.07 AS TAX_PRICE FROM CUSTOMER;

// CONCATENAR DOIS VALORES USANDO "||"
SELECT NAME, CITY ||','|| STATE AS LOCATION FROM CUSTOMER;
SELECT NAME ||': '|| CITY ||', '|| PRICE AS TAX_PRICE FROM CUSTOMER; 
SELECT CITY ||': '|| STATE ||', '|| PRICE AS STATE_TAX FROM CUSTOMER;

// fundamentos básicos do SQL
