// CREATE A NEW TABLE 
CREATE TABLE WEATHER_STATIONS (
    STATION_ID INTEGER PRIMARY KEY,
    STATION_NAME TEXT,
    CITY TEXT,
    STATE TEXT,
    ELEVATION_M REAL,
    REPORT_CODE TEXT,
    ACTIVE INTEGER
);

// ADICIONAR VALORES 
INSERT INTO WEATHER_STATIONS (STATION_ID, STATION_NAME, CITY, STATE, ELEVATION_M, REPORT_CODE, ACTIVE)
VALUES
(1, 'STATION ALPHA', 'SÃO PAULO', 'SP', 760.5, '513A63', 1),
(2, 'STATION BRAVO', 'CURITIBA', 'PR', 930.2, '721B44', 1),
(3, 'STATION CHARLIE', 'RECIFE', 'PE', 4.3, '298C12', 1),
(4, 'STATION DELTA', 'PORTA ALEGRE', 'RS', 10.5, '442F22', 0);

// PARA RECUPERAR VALORES DE 2010
SELECT * FROM STATION_DATA WHERE YEAR = 2010;
SELECT * FROM STATION_DATA WHERE DAY = 15;
SELECT * FROM STATION_DATA WHERE MONTH = 12;
SELECT * FROM STATION_DATA WHERE MONTH = 12 AND YEAR = 2002;
SELECT * FROM STATION_DATA WHERE MONTH = 12 AND YEAR = 2002 AND DAY = 21;
SELECT * FROM STATION_DATA WHERE MONTH > 6 AND DAY = 12 AND YEAR > 2008;
SELECT * FROM STATION_DATA WHERE DAY = 12 AND RAIN = 1;
SELECT * FROM STATION_DATA WHERE YEAR = 2002 AND MONTH = 12 AND RAIN = 1 AND THUNDER = 1;
SELECT * FROM STATION_DATA WHERE YEAR = 2002 AND MONTH = 12 AND RAIN = 1 AND THUNDER = 1 AND PRECIPITATION IS NULL;
SELECT * FROM STATION_DATA WHERE YEAR = 2002 AND MONTH = 12 AND RAIN = 1 AND THUNDER = 1 AND PRECIPITATION IS NOT NULL;
SELECT * FROM STATION_DATA WHERE YEAR BETWEEN 2002 AND 2005;
SELECT * FROM STATION_DATA WHERE YEAR = 2002 OR YEAR = 2005;
SELECT * FROM STATION_DATA WHRE REPORT_CODE IN ('202D6B');
SELECT * FROM STATION_DATA WHERE REPORT_CODE IN ('EF616A', 'B9B8B2');
SELECT * FROM STATION_DATA WHERE YEAR LIKE 2002;
SELECT * FROM STATION_DATA WHERE MONTH LIKE 12 AND YEAR LIKE 2002;
SELECT * FROM STATION_DATA WHERE YEAR = 2010;
SELECT * FROM STATION_DATA WHERE MONTH IN (3, 6, 9);
SELECT * FROM STATION_DATA WHERE REPORT_CODE = '513A63';
SELECT * FROM STATION_DATA WHERE REPORT_CODE LIKE 'A%';
SELECT * FROM STATION_DATA WHERE REPORT_CODE LIKE 'A1%';
SELECT * FROM STATION_DATA WHERE REPORT_CODE LIKE 'A12%';
SELECT * FROM STATION_DATA WHERE TORNADO AND HAIL;
SELECT * FROM STATION_DATA WHERE TORNADO = 0 AND HAIL = 0;
SELECT * FROM STATION_DATA WHERE SNOW_DEPTH IS NULL;
SELECT * FROM STATION_DATA WHERE SNOW_DEPTH IS NOT NULL;
SELECT * FROM STATION_DATA WHERE PRECIPITATION IS NULL OR PRECIPITATION  <= 0.5;
SELECT * FROM STATION_DATA WHERE (RAIN = 1 AND TEMPERATURE <= 32) OR SNOW_DEPTH > 0;