-- O INNER JOIN mescla registros onde há uma correspondência em ambas as tabelas. Por exemplo:
SELECT 
    ORDER_ID, 
    CUSTOMER.CUSTOMER_ID,
    ORDER_DATE,
    SHIP_DATE,
    NAME,
    STREET_ADRESS,
    CITY, 
    STATE, 
    ZIP,
    PRODUCT_ID,
    ORDER_QTY
FROM CUSTOMER
INNER JOIN CUSTOMER_ORDER ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID;


SELECT ORDER_ID, CUSTOMER.CUSTOMER_ID,
ORDER_DATE, SHIP_DATE, NAME,
STREET_ADDRESS,
CITY, STATE, ZIP, PRODUCT_ID, ORDER_QTY
FROM CUSTOMER
INNER JOIN CUSTOMER_ORDER ON 
CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID;

-- Em cenários onde você deseja incluir todos os registros de uma tabela, independentemente de haver uma correspondência na outra, usa-se um LEFT JOIN:
SELECT CUSTOMER.CUSTOMAR_ID, 
    NAME AS CUSTOMER_NAME
FROM 
    CUSTOMER 
LEFT JOIN CUSTOMER_ORDER ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
WHERE ORDER_ID IS NULL;

-- Relações complexas muitas vezes requerem múltiplas junções. POR EXEMPLO, unir as tabelas CUSTOMER, CUSTOMER_ORDER e PRODUCT permite uma recuperação abrangente de dados:
SELECT 
    ORDER_ID, CUSTOMER.CUSTOMER_ID, 
    NAME AS CUSTOMER_NAME, ORDER_QTY, ORDER_QTY*PRICE AS REVENUE
FROM CUSTOMER 
INNER JOIN CUSTOMER_ORDER ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
INNER JOIN PRODUCT ON CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID;

-- Para agregar dados por cliente enquanto une múltiplas tabelas:
SELECT 
    CUSTOMER_NAME, COALESCE(SUM(ORDER_QTY*PRICE), 0) AS TOTAL_REVENUE
FROM 
    CUSTOMER 
LEFT JOIN CUSTOMER_ORDER ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID 
LEFT JOIN PRODUCT ON CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY 1, 2;

-- A operação INNER JOIN combina duas tabelas com base em um campo comum, tipicamente usando chaves como CUSTOMER_ID.
SELECT 
    ORDER_ID, CUSTOMER.CUSTOMER_ID, ORDER_DATE, ...
FROM 
    FROM CUSTOMER 
INNER JOIN CUSTOMER_ORDER ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID;

-- O LEFT JOIN mantém todos os registros da tabela à esquerda (por exemplo, CUSTOMER), mesmo que não haja correspondência na tabela à direita (por exemplo, CUSTOMER_ORDER).
-- Isso ajuda a incluir clientes sem pedidos:
SELECT 
    ORDER_ID, CUSTOMER.CUSTOMER_ID, ORDER_DATE
FROM CUSTOMER
LEFT JOIN CUSTOMER_ORDER ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID;
